### ISSUE TITLE
Error Generating fayde.json

### ISSUE THREAD

**Issue by ssickles** [BSick7/generator-fayde#1]
The fayde application generator seems to be having trouble generating the fayde.json at the end of the process. Starting from a blank directory, I ran "yo fayde" and got the following:

[?] Your project name: Map
Map
[?] Which modules would you like to include? exjs, Fayde.Controls
   create .bowerrc
   create bower.json
   create package.json
   create Gruntfile.js
   create app/default.html
   create app/default.fap
   create app/ViewModels/MainViewModel.ts
bower fayde#\*                   cached git://github.com/wsick/Fayde.git#0.16.15
bower fayde#\*                 validate 0.16.15 against git://github.com/wsick/Fayde.git#*
bower minerva#~0.4.7            cached git://github.com/wsick/minerva.git#0.4.8
bower minerva#~0.4.7          validate 0.4.8 against git://github.com/wsick/minerva.git#~0.4.7
bower nullstone#~0.3.9          cached git://github.com/wsick/nullstone.git#0.3.10
bower nullstone#~0.3.9        validate 0.3.10 against git://github.com/wsick/nullstone.git#~0.3.9
bower requirejs#~2.1.15         cached git://github.com/jrburke/requirejs-bower.git#2.1.15
bower requirejs#~2.1.15       validate 2.1.15 against git://github.com/jrburke/requirejs-bower.git#~2.1.15
bower requirejs-text#~2.0.12    cached git://github.com/requirejs/text.git#2.0.13
bower requirejs-text#~2.0.12  validate 2.0.13 against git://github.com/requirejs/text.git#~2.0.12
bower perfex#~0.1.0             cached git://github.com/wsick/perfex.git#0.1.3
bower perfex#~0.1.0           validate 0.1.3 against git://github.com/wsick/perfex.git#~0.1.0
bower exjs#\*                not-cached git://github.com/bsick7/exjs.git#*
bower exjs#\*                   resolve git://github.com/bsick7/exjs.git#*
bower fayde.controls#~0.16.0       not-cached git://github.com/wsick/Fayde.Controls.git#~0.16.0
bower fayde.controls#~0.16.0          resolve git://github.com/wsick/Fayde.Controls.git#~0.16.0
bower fayde.controls#~0.16.0         download https://github.com/wsick/Fayde.Controls/archive/0.16.5.tar.gz
bower exjs#\*                         download https://github.com/bsick7/exjs/archive/0.2.8.tar.gz
bower exjs#\*                          extract archive.tar.gz
bower exjs#\*                         resolved git://github.com/bsick7/exjs.git#0.2.8
bower fayde.controls#~0.16.0          extract archive.tar.gz
bower fayde.controls#~0.16.0     invalid-meta fayde.controls is missing "main" entry in bower.json
bower fayde.controls#~0.16.0         resolved git://github.com/wsick/Fayde.Controls.git#0.16.5
bower fayde#~0.16.8                   install fayde#0.16.15
bower minerva#~0.4.7                  install minerva#0.4.8
bower requirejs-text#~2.0.12          install requirejs-text#2.0.13
bower nullstone#~0.3.9                install nullstone#0.3.10
bower requirejs#~2.1.15               install requirejs#2.1.15
bower perfex#~0.1.0                   install perfex#0.1.3
bower exjs#~0.2.8                     install exjs#0.2.8
bower fayde.controls#~0.16.0          install fayde.controls#0.16.5
bower                             postinstall unify update
bower                                  ENOENT spawn ENOENT

Stack trace:
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.25
OS: Darwin 13.4.0 x64

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at EventEmitter.emit (events.js:74:15)
    at done (/usr/local/lib/node_modules/generator-fayde/node_modules/yeoman-generator/lib/base.js:383:23)
    at null.<anonymous> (/usr/local/lib/node_modules/generator-fayde/node_modules/yeoman-generator/lib/actions/install.js:44:7)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)

The app folder did not contain the fayde.json file and after adding this the app seems to run fine.

**Comment by BSick7** [comment]
This is due to `fayde-unify` not being installed globally. `npm install -g fayde-unify`.  Working on removing this dependency.
